/*
 * File: app/view/GridGuideView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MythTouch.view.GridGuideView', {
    extend: 'Ext.Container',
    alias: 'widget.gridguideview',
    requires: [
        'MythTouch.view.GuideDataView'
    ],

    config: {
        ui: 'light',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Guide',
                items: [
                    {
                        xtype: 'selectfield',
                        width: '75%',
                        labelWidth: '35%',
                        name: 'GuideStartTime',
                        options: [
                            {
                                text: '00:00',
                                value: '00:00'
                            },
                            {
                                text: '01:00',
                                value: '01:00'
                            },
                            {
                                text: '02:00',
                                value: '02:00'
                            },
                            {
                                text: '03:00',
                                value: '03:00'
                            },
                            {
                                text: '04:00',
                                value: '04:00'
                            },
                            {
                                text: '05:00',
                                value: '05:00'
                            },
                            {
                                text: '06:00',
                                value: '06:00'
                            },
                            {
                                text: '07:00',
                                value: '07:00'
                            },
                            {
                                text: '08:00',
                                value: '08:00'
                            },
                            {
                                text: '09:00',
                                value: '09:00'
                            },
                            {
                                text: '10:00',
                                value: '10:00'
                            },
                            {
                                text: '11:00',
                                value: '11:00'
                            },
                            {
                                text: '12:00',
                                value: '12:00'
                            },
                            {
                                text: '13:00',
                                value: '13:00'
                            },
                            {
                                text: '14:00',
                                value: '14:00'
                            },
                            {
                                text: '15:00',
                                value: '15:00'
                            },
                            {
                                text: '16:00',
                                value: '16:00'
                            },
                            {
                                text: '17:00',
                                value: '17:00'
                            },
                            {
                                text: '18:00',
                                value: '18:00'
                            },
                            {
                                text: '19:00',
                                value: '19:00'
                            },
                            {
                                text: '20:00',
                                value: '20:00'
                            },
                            {
                                text: '21:00',
                                value: '21:00'
                            },
                            {
                                text: '22:00',
                                value: '22:00'
                            },
                            {
                                text: '23:00',
                                value: '23:00'
                            }
                        ],
                        flex: 1,
                        align: 'right'
                    }
                ]
            },
            {
                xtype: 'container',
                docked: 'top',
                html: '',
                id: 'ProgramTimes',
                itemId: 'mycontainer4',
                tpl: [
                    ''
                ],
                layout: {
                    type: 'vbox'
                },
                listeners: [
                    {
                        fn: function(component, options) {
                            component.setHtml('<table width="100%" border="0" cellpadding="4" cellspaceing="2" class="x-toolbar-dark"><tr><td class="x-channel-heading">Channel</td>');
                            for (i=0; i < 3; i++) {
                                for (j=0; j < 3; j++) {
                                    component.setHtml(component.getHtml() + '<td class="x-channel x-channel-heading-time">' + zeroPad(i,2) + ':' + zeroPad(j*15,2) +'</td>');
                                }
                            } 
                            component.setHtml(component.getHtml() + '</tr></table>');
                        },
                        event: 'initialize'
                    }
                ]
            },
            {
                xtype: 'guidedataview',
                itemTpl: [
                    '<table width="100%" border="0" cellpadding="4" cellspacing="2" class="list small">',
                    '<tbody>',
                    '<tpl for=".">',
                    '   <tr>',
                    '        <td class="x-channel-heading" halign="center"><img src="{IconURL}" style="padding: 5px;"><br />{ChannelName}</td>',
                    '        <tpl for="Programs">',
                    '                 <td class="program small cat_{[ values.Category.split("/")[0].toTitleCase().replace(" ", "_") ]} record_{[ recStatus[values.Recording.Status].toLowerCase().replace(" ", "_") ]}" valign="top">{Title}<tpl if="SubTitle != \'\'">:<br />{SubTitle}<br /></tpl>',
                    '{%',
                    'console.log("Programs Count:", values.Programs);',
                    '',
                    ' for (i =1; i < values.Stars; i++) {',
                    '    if (i == 1) {',
                    '       out.push("<br />");',
                    '     }',
                    '     out.push("★");',
                    '}',
                    '%}',
                    '</td>',
                    '        </tpl>',
                    '  </tr>',
                    '</tpl>',
                    '</table>'
                ]
            }
        ]
    }

});