/*
 * File: app/view/GridGuideView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MythTouch.view.GridGuideView', {
    extend: 'Ext.Container',
    alias: 'widget.gridguideview',
    requires: [
        'MythTouch.view.GuideDataView'
    ],

    config: {
        ui: 'light',
        layout: {
            type: 'fit'
        },
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Guide',
                items: [
                    {
                        xtype: 'selectfield',
                        width: '75%',
                        labelWidth: '35%',
                        name: 'GuideStartTime',
                        options: [
                            {
                                text: '00:00',
                                value: '00:00'
                            },
                            {
                                text: '01:00',
                                value: '01:00'
                            },
                            {
                                text: '02:00',
                                value: '02:00'
                            },
                            {
                                text: '03:00',
                                value: '03:00'
                            },
                            {
                                text: '04:00',
                                value: '04:00'
                            },
                            {
                                text: '05:00',
                                value: '05:00'
                            },
                            {
                                text: '06:00',
                                value: '06:00'
                            },
                            {
                                text: '07:00',
                                value: '07:00'
                            },
                            {
                                text: '08:00',
                                value: '08:00'
                            },
                            {
                                text: '09:00',
                                value: '09:00'
                            },
                            {
                                text: '10:00',
                                value: '10:00'
                            },
                            {
                                text: '11:00',
                                value: '11:00'
                            },
                            {
                                text: '12:00',
                                value: '12:00'
                            },
                            {
                                text: '13:00',
                                value: '13:00'
                            },
                            {
                                text: '14:00',
                                value: '14:00'
                            },
                            {
                                text: '15:00',
                                value: '15:00'
                            },
                            {
                                text: '16:00',
                                value: '16:00'
                            },
                            {
                                text: '17:00',
                                value: '17:00'
                            },
                            {
                                text: '18:00',
                                value: '18:00'
                            },
                            {
                                text: '19:00',
                                value: '19:00'
                            },
                            {
                                text: '20:00',
                                value: '20:00'
                            },
                            {
                                text: '21:00',
                                value: '21:00'
                            },
                            {
                                text: '22:00',
                                value: '22:00'
                            },
                            {
                                text: '23:00',
                                value: '23:00'
                            }
                        ],
                        flex: 1,
                        align: 'right'
                    }
                ]
            },
            {
                xtype: 'guidedataview'
            }
        ]
    }

});