/*
 * File: app/view/GuideListChannels.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MythTouch.view.GuideListChannels', {
    extend: 'Ext.dataview.List',
    alias: 'widget.guidelistchannels',

    config: {
        ui: 'round',
        store: 'ProgramGuide',
        onItemDisclosure: true,
        itemTpl: [
            '<div style="text-align: middle;"><img src="{IconURL}" style="width: 35px;"  />{ChanNum} - {ChannelName}</div>'
        ],
        listeners: [
            {
                fn: 'onListDisclose',
                event: 'disclose'
            }
        ]
    },

    onListDisclose: function(list, record, target, index, e, options) {
        console.log("List: ", list);
        console.log("Record: ", record);
        console.log("Target: ", target);
        console.log("Index: ", index);
        console.log("E: ", e);
        console.log("Options: ", options);
        console.log("this.data: ", this.data);
    }

});