/*
 * File: app/view/GuideDataView.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MythTouch.view.GuideDataView', {
    extend: 'Ext.dataview.DataView',
    alias: 'widget.guidedataview',

    config: {
        html: '<table width="100%" border="0" cellpadding="4" cellspaceing="2" class="list small"><tr><td class="x-channel">Channel</td><td>00:00</td><td>00:00</td><td>00:00</td><td>00:00</td></tr></table>',
        ui: 'light',
        scrollable: 'both',
        emptyText: 'Something went wrong, I can\'t find anything!',
        store: 'ProgramGuide',
        useComponents: false,
        itemTpl: [
            '<table width="100%" border="0" cellpadding="4" cellspacing="2" class="list small">',
            '<tbody>',
            '<tpl for=".">',
            '   <tr>',
            '        <td class="x-channel" halign="center"><img src="{IconURL}" style="padding: 5px;"><br />{ChannelName}</td>',
            '        <tpl for="Programs">',
            '                 <td class="program small cat_{[ values.Category.split("/")[0].toTitleCase().replace(" ", "_") ]} record_{[ recStatus[values.Recording.Status].toLowerCase().replace(" ", "_") ]}" valign="top">{Title}<tpl if="SubTitle != \'\'">:<br />{SubTitle}<br /></tpl>',
            '{%',
            ' for (i =1; i < values.Stars; i++) {',
            '    if (i == 1) {',
            '       out.push("<br />");',
            '     }',
            '     out.push("★");',
            '}',
            '%}',
            '</td>',
            '        </tpl>',
            '  </tr>',
            '</tpl>',
            '</table>'
        ]
    }

});