/*
 * File: app/view/Viewport.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MythTouch.view.Viewport', {
    extend: 'Ext.tab.Panel',
    requires: [
        'MythTouch.view.ScheduledView',
        'MythTouch.view.GridGuideView'
    ],

    config: {
        items: [
            {
                xtype: 'container',
                html: '<span align="center"><h1>MythTouch</h1></span> <div>Welcome to MythTouch your touch based interface to the scheduling side of MythTV</div> <div>Select one of the tabs at the bottom to get started</div>',
                styleHtmlContent: true,
                ui: 'light',
                scrollable: true,
                title: 'Welcome',
                iconCls: 'info'
            },
            {
                xtype: 'scheduledView',
                title: 'Schedule',
                iconCls: 'time'
            },
            {
                xtype: 'gridguideview',
                title: 'Guide',
                iconCls: 'bookmarks'
            }
        ],
        tabBar: {
            docked: 'bottom'
        }
    }

});