/*
 * File: app/model/UpComingProgramModel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MythTouch.model.UpComingProgramModel', {
    extend: 'Ext.data.Model',
    uses: [
        'MythTouch.model.RecordingModel',
        'MythTouch.model.UpComingChannelModel'
    ],
    config: {
        fields: [
            {
                name: 'StartTime'
            },
            {
                name: 'EndTime'
            },
            {
                name: 'Title'
            },
            {
                name: 'SubTitle'
            },
            {
                name: 'Category'
            },
            {
                name: 'Repeat'
            },
            {
                name: 'VideoProps'
            },
            {
                name: 'AudioProps'
            },
            {
                name: 'SubProps'
            },
            {
                name: 'SeriesId'
            },
            {
                name: 'ProgramId'
            },
            {
                name: 'Stars'
            },
            {
                name: 'FileName'
            },
            {
                name: 'HostName'
            },
            {
                name: 'Airdate'
            },
            {
                name: 'Description'
            },
            {
                name: 'Inetref'
            },
            {
                name: 'Season'
            },
            {
                name: 'Episode'
            }
        ],
        hasOne: [
            {
                associationKey: 'Recording',
                model: 'MythTouch.model.RecordingModel',
                associatedName: 'Recording'
            },
            {
                associationKey: 'Channel',
                model: 'MythTouch.model.UpComingChannelModel',
                associatedName: 'Channel'
            }
        ]
    }
});