/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'ChannelModel',
        'ProgramModel',
        'RecordingModel',
        'UpComingProgramModel',
        'UpComingChannelModel'
    ],
    stores: [
        'UpComingProgramStore',
        'ProgramGuide'
    ],
    views: [
        'RecordingDetail',
        'GuideView',
        'GuideListChannels',
        'GuideListPrograms',
        'Viewport',
        'GridGuideView',
        'GuideDataView',
        'ScheduledList',
        'ScheduledView',
        'ProgramTimes'
    ],
    glossOnIcon: true,
    name: 'MythTouch',
    controllers: [
        'ScheduledView',
        'GridGuideView'
    ],

    launch: function() {

        Ext.create('MythTouch.view.Viewport', {fullscreen: true});
    }

});
