/*
 * File: app/view/ScheduleDetail.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MythTouch.view.ScheduleDetail', {
    extend: 'Ext.Container',
    alias: 'widget.scheduleDetail',

    config: {
        styleHtmlContent: true,
        scrollable: 'vertical',
        tpl: [
            '<div class="schedule-detail">',
            '<div class="schedule-detail-recording-time">{[ Ext.Date.format(Ext.Date.parse(values.Recording.StartTs, "c"), "D d M") ]}, {[ Ext.Date.format(Ext.Date.parse(values.Recording.StartTs, "c"), "H:i")  ]} - {[ Ext.Date.format(Ext.Date.parse(values.Recording.EndTs, "c"), "H:i") ]}<br /></div>',
            '<div class="schedule-detail-recording-channel">{Channel.ChannelName}<br /></div>',
            '<div class="schedule-detail-title" style="clear: both;">{Title}</div>',
            '<div class="schedule-detail-subtitle">{SubTitle}</div>',
            '<div class="schedule-detail-description">{Description}</div>',
            '<div>This showing {[ recStatus[values.Recording.Status] ]}<br /><br />{[ recTypes[values.Recording.RecType] ]}&nbsp;<tpl if="Recording.RecType = \'4\'">{Channel.ChannelName}</tpl></div>',
            '</div>'
        ]
    }

});