/*
 * File: app/store/UpComingProgramStore.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MythTouch.store.UpComingProgramStore', {
    extend: 'Ext.data.Store',
    requires: [
        'MythTouch.model.UpComingProgramModel'
    ],

    config: {
        autoLoad: true,
        model: 'MythTouch.model.UpComingProgramModel',
        storeId: 'UpComingProgramStore',
        proxy: {
            type: 'ajax',
            enablePagingParams: false,
            extraParams: {
                ShowAll: true
            },
            limitParam: 'Count',
            startParam: 'StartIndex',
            url: 'xml-proxy.php?/Dvr/GetUpcomingList',
            reader: {
                type: 'json',
                rootProperty: 'ProgramList.Programs',
                totalProperty: 'Count'
            }
        },
        grouper: {
            groupFn: function(record) {
                return Ext.Date.format(Ext.Date.parseDate(record.get("StartTime"), "c"), "l j F Y");
            },
            transform: function(item) {
                return Ext.Date.format(Ext.Date.parseDate(item, "c"), "Ymd");
            },
            sortProperty: 'StartTime'
        }
    }
});